character = alpha | digit ;

alpha = "A" | "B" | "C" | "D" | "E" | "F" | "G"
      | "H" | "I" | "J" | "K" | "L" | "M" | "N"
      | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
      | "V" | "W" | "X" | "Y" | "Z"
      | "a" | "b" | "c" | "d" | "e" | "f" | "g"
      | "h" | "i" | "j" | "k" | "l" | "m" | "n"
      | "o" | "p" | "q" | "r" | "s" | "t" | "u"
      | "v" | "w" | "x" | "y" | "z" ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

identifier = (character | "_"), {character | "_"};

string = "'", { character | "\\", "'" }, "'"
         | '"', { character | "\\", '"' }, '"';

i8 = "-128".."127";

i16 = "-32768".."32767";

i32 = "-2147483648".."2147483647";

i64 = "-9223372036854775808".."9223372036854775807";

u8 = "0".."255";

u16 = "0".."65535";

u32 = "0".."4294967295";

u64 = "0".."18446744073709551615";

int = i8 | u8 | i16 | u16 | i32 | u32 | i64 | u64;

type = int | string;

assignment = identifier, [type], "=", expression;

block = "{", [statement], "}";

if = "if", expression, ":", block, [else];

else = "else", ":", block;

while = "while", expression, ":", block;

for = "for", identifier, "in", identifier, ":", block;

ops = "==" | "!=" | "<" | ">" | "<=" | ">=" ;

math_ops = "+" | "-" | "*" | "/" ;

term = factor, {("*" | "/"), factor};

factor = literal | identifier | "(", expression, ")";

function = "fn", identifier, "(", [parameters], ")", ":", block;

function_call = identifier, "(", [parameters], ")";

parameters = {identifier, {",", identifier}};

decorator = "@", identifier, [parameters];

class = "class", identifier, ":", class_body;

class_body = {class_property | class_method};

class_property = assignment;

class_method = function;

conditional_statement = if;

loop_statement = while, for;

class_statement = class_property | class_method;

expression = function_call, identifier, string, term; 

statement = expression, assignment, conditional_statement, loop_statement, class_statement;

